name:        "Stratosphere | Above the Clouds"
markdown:    redcarpet
pygments:    true
timezone:    "Europe/Berlin"
safe:        true
lsi:         false
# see https://github.com/mojombo/jekyll/issues/332
baseurl:     /ozone
