name:               "Stratosphere | Above the Clouds"
markdown:           redcarpet
pygments:           true
timezone:           "Europe/Berlin"
safe:               true
lsi:                false

# pagination
paginate:           10
paginate_path:      "blog/page-:num"

# see https://github.com/mojombo/jekyll/issues/332
baseurl:            ""

# Stratosphere related variables
current_snapshot:       "0.4-SNAPSHOT"
current_snapshot_yarn:  "0.4-hadoop2-SNAPSHOT"
current_stable:         "0.4-rc1"
current_stable_yarn:    "0.4-rc1-hadoop2"
#used in download and quickstart
current_stable_dl:      "https://github.com/stratosphere/stratosphere/releases/download/v0.4-rc1/stratosphere-0.4-rc1.tgz"
current_stable_dl_yarn: "https://github.com/stratosphere/stratosphere/releases/download/v0.4-rc1/stratosphere-0.4-rc1-hadoop2.tgz"
current_stable_uberjar: "https://github.com/stratosphere/stratosphere/releases/download/v0.4-rc1/stratosphere-dist-0.4-rc1-yarn-uberjar.jar"
